package gestionrecette;

import static gestionrecette.GestionRecette.lesRecettes;
import static gestionrecette.GestionRecette.lesTypes;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jeremy
 */
public class MenuConsultRecettes extends javax.swing.JFrame
{

    /**
     * Creates new form MenuConsultRecettes
     */
    private int position;
    public MenuConsultRecettes()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        position=0;
        
        inputID.setEditable(false);
        inputNom.setEditable(false);
        inputTpsPrep.setEditable(false);
        inputTpsCuiss.setEditable(false);
        inputNiveauDifficulte.setEditable(false);
        list1.setEditable(false);
        list2.setEditable(false);
        list3.setEditable(false);
        list4.setEditable(false);
        list5.setEditable(false);
        list6.setEditable(false);
        list7.setEditable(false);
        list8.setEditable(false);
        inputType.setEditable(false);
        
        if(!GestionRecette.lesRecettes.isEmpty())
        {
            for(Recette laRecette : lesRecettes)
            {
                afficherRecette(laRecette);
                break;
            }
            this.btnPrec.setEnabled(false);
            if(this.position+1>=GestionRecette.lesRecettes.size())
            {
                this.btnSuiv.setEnabled(false);
            }
        }
    }
    
    private void afficherRecette(Recette laRecette)
    {
        this.inputID.setText(Integer.toString(laRecette.getIdRecette()));
        this.inputNom.setText(laRecette.getNomRecette());
        this.inputTpsPrep.setText(laRecette.getTempsPreparation());
        this.inputTpsCuiss.setText(laRecette.getTempsCuisson());
        this.inputNiveauDifficulte.setText(Integer.toString(laRecette.getNiveauDifficulte()));
        this.inputType.setText(Integer.toString(laRecette.getIdType()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputID = new javax.swing.JTextField();
        btnAnnuler = new javax.swing.JButton();
        labelNom = new javax.swing.JLabel();
        list1 = new javax.swing.JComboBox();
        inputNom = new javax.swing.JTextField();
        list2 = new javax.swing.JComboBox();
        inputTpsPrep = new javax.swing.JTextField();
        list3 = new javax.swing.JComboBox();
        labelTpsPrep = new javax.swing.JLabel();
        list4 = new javax.swing.JComboBox();
        labelTpsCuiss = new javax.swing.JLabel();
        list5 = new javax.swing.JComboBox();
        inputTpsCuiss = new javax.swing.JTextField();
        list6 = new javax.swing.JComboBox();
        labelNiveauDifficulte = new javax.swing.JLabel();
        list7 = new javax.swing.JComboBox();
        inputNiveauDifficulte = new javax.swing.JTextField();
        list8 = new javax.swing.JComboBox();
        labelTitre = new javax.swing.JLabel();
        labelAliments = new javax.swing.JLabel();
        labelAliments1 = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        btnPrec = new javax.swing.JButton();
        btnSuiv = new javax.swing.JButton();
        inputType = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        labelNom.setText("Nom :");

        list1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        labelTpsPrep.setText("Temps de préparation :");

        list4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        labelTpsCuiss.setText("Temps de cuisson :");

        list5.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list6.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        labelNiveauDifficulte.setText("Niveau de difficulté :");

        list7.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list8.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        labelTitre.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelTitre.setText("CRÉATION D'UNE RECETTE");

        labelAliments.setText("Aliments :");

        labelAliments1.setText("Type :");

        labelID.setText("ID :");

        btnPrec.setText("Précédent");
        btnPrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecActionPerformed(evt);
            }
        });

        btnSuiv.setText("Suivant");
        btnSuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(labelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnPrec)
                        .addGap(29, 29, 29)
                        .addComponent(btnAnnuler)
                        .addGap(33, 33, 33)
                        .addComponent(btnSuiv))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAliments)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelID)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNom)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelTpsPrep)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputTpsPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelTpsCuiss)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputTpsCuiss, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(labelAliments1)
                                                    .addComponent(labelNiveauDifficulte))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(inputNiveauDifficulte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTpsPrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTpsPrep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTpsCuiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTpsCuiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNiveauDifficulte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNiveauDifficulte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAliments1)
                    .addComponent(inputType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAliments)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrec)
                    .addComponent(btnAnnuler)
                    .addComponent(btnSuiv))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // Affichage du menu de saisie des offres de stage
        java.awt.EventQueue.invokeLater(new Runnable()
            {
                public void run()
                {
                    try
                    {
                        new MenuPrincipal().setVisible(true);
                    }
                    catch(IOException ex)
                    {
                        Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    catch(ClassNotFoundException ex)
                    {
                        Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
            // ***************************
            this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnPrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecActionPerformed
        if(this.position>0) {
            afficherRecette(GestionRecette.lesRecettes.get(position-1));
            this.position-=1;
            if(this.position==0) {
                this.btnPrec.setEnabled(false);
            }
            this.btnSuiv.setEnabled(true);
        }
    }//GEN-LAST:event_btnPrecActionPerformed

    private void btnSuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivActionPerformed
        if(this.position+1<GestionRecette.lesRecettes.size()) {
            afficherRecette(GestionRecette.lesRecettes.get(position+1));
            this.position+=1;
            this.btnPrec.setEnabled(true);
            if(this.position>=GestionRecette.lesRecettes.size()) {
                this.btnSuiv.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnSuivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuConsultRecettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuConsultRecettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuConsultRecettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuConsultRecettes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuConsultRecettes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnPrec;
    private javax.swing.JButton btnSuiv;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputNiveauDifficulte;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputTpsCuiss;
    private javax.swing.JTextField inputTpsPrep;
    private javax.swing.JTextField inputType;
    private javax.swing.JLabel labelAliments;
    private javax.swing.JLabel labelAliments1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNiveauDifficulte;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JLabel labelTpsCuiss;
    private javax.swing.JLabel labelTpsPrep;
    private javax.swing.JComboBox list1;
    private javax.swing.JComboBox list2;
    private javax.swing.JComboBox list3;
    private javax.swing.JComboBox list4;
    private javax.swing.JComboBox list5;
    private javax.swing.JComboBox list6;
    private javax.swing.JComboBox list7;
    private javax.swing.JComboBox list8;
    // End of variables declaration//GEN-END:variables
}
