package gestionrecette;

import static gestionrecette.GestionRecette.lesAliments;
import static gestionrecette.GestionRecette.lesRecettes;
import static gestionrecette.GestionRecette.lesTypes;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author jeremy
 */
public class MenuSaisieRecette extends javax.swing.JFrame
{

    /**
     * Creates new form MenuSaisieRecette
     */
    public MenuSaisieRecette()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Construction du menu déroulant de la liste des aliments
        list1.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list1.addItem(unAliment.getNomAliment());
        }
        list2.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list2.addItem(unAliment.getNomAliment());
        }
        list3.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list3.addItem(unAliment.getNomAliment());
        }
        list4.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list4.addItem(unAliment.getNomAliment());
        }
        list5.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list5.addItem(unAliment.getNomAliment());
        }
        list6.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list6.addItem(unAliment.getNomAliment());
        }
        list7.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list7.addItem(unAliment.getNomAliment());
        }
        list8.addItem("");
        for(Aliment unAliment : lesAliments)
        {
            list8.addItem(unAliment.getNomAliment());
        }
        
        listType.addItem("");
        for(gestionrecette.Type unType : lesTypes)
        {
            listType.addItem(unType.getLibelleType());
        }
        // **********************************************************
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitre = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        labelNom = new javax.swing.JLabel();
        inputNom = new javax.swing.JTextField();
        inputTpsPrep = new javax.swing.JTextField();
        labelTpsPrep = new javax.swing.JLabel();
        labelTpsCuiss = new javax.swing.JLabel();
        inputTpsCuiss = new javax.swing.JTextField();
        labelNiveauDifficulte = new javax.swing.JLabel();
        inputNiveauDifficulte = new javax.swing.JTextField();
        labelAliments = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();
        list1 = new javax.swing.JComboBox();
        list2 = new javax.swing.JComboBox();
        list3 = new javax.swing.JComboBox();
        list4 = new javax.swing.JComboBox();
        list5 = new javax.swing.JComboBox();
        list6 = new javax.swing.JComboBox();
        list7 = new javax.swing.JComboBox();
        list8 = new javax.swing.JComboBox();
        labelAliments1 = new javax.swing.JLabel();
        listType = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitre.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelTitre.setText("CRÉATION D'UNE RECETTE");

        labelID.setText("ID :");

        labelNom.setText("Nom :");

        labelTpsPrep.setText("Temps de préparation :");

        labelTpsCuiss.setText("Temps de cuisson :");

        labelNiveauDifficulte.setText("Niveau de difficulté :");

        labelAliments.setText("Aliments :");

        btnCreate.setText("Créer");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnAnnuler.setText("Annuler");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        list1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list4.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list5.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list6.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list7.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        list8.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        labelAliments1.setText("Type :");

        listType.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(labelTitre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnCreate)
                        .addGap(111, 111, 111)
                        .addComponent(btnAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(list8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAliments)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelID)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(100, 100, 100))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelNom)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelTpsPrep)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputTpsPrep, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(labelTpsCuiss)
                                                .addGap(26, 26, 26)
                                                .addComponent(inputTpsCuiss, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(labelAliments1)
                                                    .addComponent(labelNiveauDifficulte))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(inputNiveauDifficulte, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                    .addComponent(listType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTpsPrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTpsPrep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTpsCuiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTpsCuiss))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNiveauDifficulte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNiveauDifficulte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAliments1)
                    .addComponent(listType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAliments)
                    .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(list5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnAnnuler))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        // Affichage du menu de saisie des offres de stage
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                try
                {
                    new MenuPrincipal().setVisible(true);
                }
                catch(IOException ex)
                {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                catch(ClassNotFoundException ex)
                {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        // ***************************
        this.dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String list1Field = (String)this.list1.getSelectedItem(); 
        String list2Field = (String)this.list2.getSelectedItem();
        String list3Field = (String)this.list3.getSelectedItem();
        String list4Field = (String)this.list4.getSelectedItem();
        String list5Field = (String)this.list5.getSelectedItem();
        String list6Field = (String)this.list6.getSelectedItem();
        String list7Field = (String)this.list7.getSelectedItem();
        String list8Field = (String)this.list8.getSelectedItem();
        
        if(list1Field.compareTo("") != 0 && this.inputID.getText().compareTo("") != 0 && this.inputNom.getText().compareTo("") != 0 && this.inputTpsPrep.getText().compareTo("") != 0 && this.inputTpsCuiss.getText().compareTo("") != 0 && this.inputNiveauDifficulte.getText().compareTo("") != 0)
        {
            int idAliment1 = 0;
            int idAliment2 = 0;
            int idAliment3 = 0;
            int idAliment4 = 0;
            int idAliment5 = 0;
            int idAliment6 = 0;
            int idAliment7 = 0;
            int idAliment8 = 0;
            int idType = 0;
            int idRecette = 0;
            String nomRecette = "";
            String tpsPrepRecette = "";
            String tpsCuissRecette = "";
            int niveauDifficulteRecette = 0;
            boolean error = false;

            // Id des aliments
            try
            {
                String valeur1 = list1.getSelectedItem().toString();
                idAliment1 = verifAliment(valeur1);
                
                String valeur2 = list2.getSelectedItem().toString();
                idAliment2 = verifAliment(valeur2);
                
                String valeur3 = list3.getSelectedItem().toString();
                idAliment3 = verifAliment(valeur3);
                
                String valeur4 = list4.getSelectedItem().toString();
                idAliment4 = verifAliment(valeur4);
                
                String valeur5 = list5.getSelectedItem().toString();
                idAliment5 = verifAliment(valeur5);
                
                String valeur6 = list6.getSelectedItem().toString();
                idAliment6 = verifAliment(valeur6);
                
                String valeur7 = list7.getSelectedItem().toString();
                idAliment7 = verifAliment(valeur7);
                
                String valeur8 = list8.getSelectedItem().toString();
                idAliment8 = verifAliment(valeur8);
                
                String valeur9 = listType.getSelectedItem().toString();
                idType = verifType(valeur9);
                
                idRecette = Integer.parseInt(this.inputID.getText());
                nomRecette = this.inputNom.getText();
                tpsPrepRecette = this.inputTpsPrep.getText();
                tpsCuissRecette = this.inputTpsCuiss.getText();
                niveauDifficulteRecette = Integer.parseInt(this.inputNiveauDifficulte.getText());
            }
            catch(NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Un des aliments n'est pas valide !", "Création Recette", 1);
                error = true;
            }
            
            // Si aucune erreur de saisie n'est détéctée
            if (error == false)
            {
                lesRecettes.add(new Recette(idRecette, nomRecette, tpsPrepRecette, tpsCuissRecette, niveauDifficulteRecette, idType));
                System.out.println(idRecette + ", " + nomRecette + ", " + tpsPrepRecette + ", " + tpsCuissRecette + ", " + niveauDifficulteRecette + ", " + idType);

                if (error == false)
                {
                    this.dispose();
                    // Affichage du menu principal
                    java.awt.EventQueue.invokeLater(new Runnable()
                    {
                        public void run()
                        {
                            try
                            {
                                new MenuPrincipal().setVisible(true);
                            }
                            catch(IOException ex)
                            {
                                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            catch(ClassNotFoundException ex)
                            {
                                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });
                    // ***************************
                }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Une erreur est survenue !", "Création Recette", 1);
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    public int verifAliment(String aliment)
    {
        int rep = 0;
        for(Aliment unAliment : lesAliments)
        {
            if(unAliment.getNomAliment() == aliment)
            {
                rep = unAliment.getIdAliment();
            }
        }
        return rep;
    }
    
    public int verifType(String type)
    {
        int rep = 0;
        for(gestionrecette.Type unType : lesTypes)
        {
            if(unType.getLibelleType() == type)
            {
                rep = unType.getIdType();
            }
        }
        return rep;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSaisieRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSaisieRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSaisieRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSaisieRecette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSaisieRecette().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnCreate;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputNiveauDifficulte;
    private javax.swing.JTextField inputNom;
    private javax.swing.JTextField inputTpsCuiss;
    private javax.swing.JTextField inputTpsPrep;
    private javax.swing.JLabel labelAliments;
    private javax.swing.JLabel labelAliments1;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNiveauDifficulte;
    private javax.swing.JLabel labelNom;
    private javax.swing.JLabel labelTitre;
    private javax.swing.JLabel labelTpsCuiss;
    private javax.swing.JLabel labelTpsPrep;
    private javax.swing.JComboBox list1;
    private javax.swing.JComboBox list2;
    private javax.swing.JComboBox list3;
    private javax.swing.JComboBox list4;
    private javax.swing.JComboBox list5;
    private javax.swing.JComboBox list6;
    private javax.swing.JComboBox list7;
    private javax.swing.JComboBox list8;
    private javax.swing.JComboBox listType;
    // End of variables declaration//GEN-END:variables
}
